name: auth_test
description: 0auth test app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auth0_flutter: 1.6.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.0.2
  google_fonts: ^4.0.3
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - images/logo.png
